name: ath79-builder

on:
  push:
    branches:
      - master

  jobs:
    push:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            sudo apt update
            sudo apt install build-essential ccache ecj fastjar file g++ gawk \
              gettext git java-propose-classpath libelf-dev libncurses5-dev \
              libncursesw5-dev libssl-dev python python2.7-dev python3 unzip \
              wget python3-distutils python3-setuptools rsync subversion swig \
              time xsltproc zlib1g-dev

        - name: Install feeds
          run: |
            ./scripts/feeds update -a
            ./scripts/feeds install -a

        - name: Prepare Config
          run: |
            echo CONFIG_TARGET_ath79=y > .config
            echo CONFIG_IB=y >> .config
            echo CONFIG_ALL_KMODS=y >> .config
            echo CONFIG_ALL_NONSHARED=y >> .config
            echo IGNORE_ERRORS=y >> .config
            make defconfig

        - name: Build Image
          run: make -j2
