name: ath79-builder

env:
  TARGET: ath79

on:
  push:
    branches:
      - master
  workflow_dispatch:

  jobs:
    push:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Install dependencies
          run: |
            sudo apt update
            sudo apt install build-essential ccache ecj fastjar file g++ gawk \
              gettext git java-propose-classpath libelf-dev libncurses5-dev \
              libncursesw5-dev libssl-dev python python2.7-dev python3 unzip \
              wget python3-distutils python3-setuptools rsync subversion swig \
              time xsltproc zlib1g-dev

        - name: Install feeds
          run: |
            ./scripts/feeds update -a
            ./scripts/feeds install -a

        - name: Prepare Config
          run: |
            echo CONFIG_TARGET_${{ env.TARGET }}=y > .config
            echo CONFIG_IB=y >> .config
            echo CONFIG_ALL_KMODS=y >> .config
            echo CONFIG_ALL_NONSHARED=y >> .config
            echo IGNORE_ERRORS=y >> .config
            make defconfig

        - name: Build Image
          run: make -j2

        - name: Store build logs
          if: ${{ !cancelled() }}
          uses: actions/upload-artifact@v1
          with:
            name: ${{ env.TARGET }}_logs
            path: ooutput/logs
          - name: Store build output
            uses: actions/upload-artifact@v1
            with:
              name: ${{ env.TARGET }}_img
              path: output/images
